#!/usr/bin/env node
/**
 * Builds Simplified-Chinese review mirrors from the three English static pages.
 * The output intentionally preserves markup, classes, media, layout, and JS.
 */
import { readFile, writeFile } from 'node:fs/promises';

const common = [
  ['lang="en"', 'lang="zh-CN"'],
  ['en-landing.html', 'zh-landing.html'],
  ['products.html', 'zh-products.html'],
  ['cases.html', 'zh-cases.html'],
  ["Zhongke Yong'an", '中科永安'],
  ['Product Catalog — Zhongke Yong\'an Battery Fire Safety', '产品目录——中科永安锂电池消防安全'],
  ['Case Studies — Zhongke Yong\'an Battery Fire Safety', '案例——中科永安锂电池消防安全'],
  ["Zhongke Yong'an — Lithium-Ion Battery Fire Suppression Systems", '中科永安——锂离子电池火灾抑制系统'],
  ['Battery Fire Safety', '锂电池消防安全'],
  ['Lithium-ion battery fire specialists', '锂离子电池火灾防护专家'],
  ["Built with China's State Key Laboratory for Fire Safety", '与中国火灾科学国家重点实验室联合打造'],
  ['Shipping worldwide', '面向全球供货'],
  ['Home', '首页'],
  ['Products', '产品'],
  ['Industries', '行业应用'],
  ['Case Studies', '案例'],
  ['About', '关于我们'],
  ['Request a Quote', '获取报价'],
  ['Contact', '联系我们'],
  ['Company', '公司'],
  ['Become a distributor', '成为经销商'],
  ['Battery Extinguishers', '电池灭火器'],
  ['Foam Concentrate Agents', '泡沫浓缩液'],
  ['Image-Based Detection', '图像型探测'],
  ['Auto-Tracking Monitors', '自动跟踪消防炮'],
  ['High-Pressure Water Mist', '高压细水雾'],
  ['Energy Storage', '储能'],
  ['EV &amp; Battery', '电动汽车与电池'],
  ['Transit &amp; Fleet', '交通与车队'],
  ['Data Centers', '数据中心'],
  ["About Zhongke Yong'an", '关于中科永安'],
  ["© 2026 Zhongke Yong'an Technology. All rights reserved.", '© 2026 中科永安科技。保留所有权利。'],
  ['Hefei · China &nbsp;·&nbsp; Business License', '中国合肥 &nbsp;·&nbsp; 营业执照'],
  ["Lithium-ion battery fire suppression — engineered in partnership with China's State Key Laboratory for Fire Safety.", '锂离子电池火灾抑制解决方案——与中国火灾科学国家重点实验室合作研发。'],
  ['Open menu', '打开菜单'],
  ['Tiananmen District', '天安门地区'],
  ['China Railway', '中国铁建'],
  ['State Grid', '国家电网'],
  ['Three Gorges', '三峡'],
  ['Xiamen Bus Group', '厦门公交集团'],
  ['Lithium-Battery Safety Initiative', '锂电池安全专项'],
  ['Construction Group — HQ Fire-Safety Modernisation', '集团——总部消防安全升级'],
  ['Yantai Storage Hub — 1 GW / 2 GWh ESS', '烟台储能枢纽——1 GW / 2 GWh 储能项目'],
  ['Muping Offshore Wind — Companion Storage', '牟平海上风电——配套储能'],
  ['Training Tower — Fire-Safety Deployment', '培训大楼——消防安全部署'],
  ['Compressed-Air Foam System (CAFS) — Lithium', '锂电池压缩空气泡沫系统（CAFS）'],
  ['Tiananmen District Lithium-Battery Safety Initiative', '天安门地区锂电池安全专项'],
  ['China Railway Construction HQ fire-safety modernisation', '中国铁建总部消防安全升级'],
  ['Three Gorges Muping Offshore Wind + Storage', '三峡牟平海上风电 + 储能'],
  ['Fire-safety protection for electric-bus parking, charging, and maintenance yards at a municipal transit operator, engineered around lithium-ion thermal-runaway risk.', '为市政公交运营方的电动公交停放、充电和维修场地提供消防安全防护，围绕锂离子电池热失控风险设计。'],
  ['Municipal transit', '市政交通'],
  ['new-energy depot', '新能源场站'],
  ['Grid-Scale ESS', '电网级储能'],
  ['Product Catalog', '产品目录'],
  ['National', '全国'],
  ['Lithium-Battery Dedicated Fire Extinguisher', '锂电池专用灭火器'],
  ['Available sizes:', '可选规格：'],
  ['Configurations:', '配置：'],
  ['hand-cart and fixed configurations on request', '可按需提供手推式和固定式配置'],
  ['Class A', 'A 类'],
  ['e.g. +1 415 ...', '例如：+86 10 ...'],
  ['e.g. United States', '例如：中国'],
  ['standard', '标准型'],
  ['explosion-proof', '防爆型'],
];

const landing = [
  ["Zhongke Yong'an — Lithium-Ion Battery Fire Suppression Systems", '中科永安——锂离子电池火灾抑制系统'],
  ["Purpose-built fire suppression for lithium-ion battery hazards. Detection, foam agents, and extinguisher systems engineered with China's State Key Lab for Fire Safety. Request a consultation.", '专为锂离子电池火灾风险打造的火灾抑制解决方案。涵盖探测、泡沫药剂与灭火设备；与中国火灾科学国家重点实验室合作研发。欢迎咨询。'],
  ['Purpose-Built for Lithium-Ion Fires', '专为锂离子电池火灾打造'],
  ['Stop battery thermal runaway before it takes out the asset.', '在热失控损毁资产前，将其阻断。'],
  ['Conventional extinguishers and clean agents do not cool a lithium-ion cell fast enough to stop thermal runaway from spreading pack-to-pack. Our foam agents, compressed-air foam systems, and image-based flame detectors are engineered for exactly that failure mode — and deployed at GWh-scale energy-storage sites, transit depots, and national security zones.', '常规灭火器与洁净气体灭火剂无法足够快地冷却锂离子电芯，难以阻止热失控在电池包之间蔓延。我们的泡沫药剂、压缩空气泡沫系统和图像型火焰探测器正是针对这一失效模式研发，并已部署于吉瓦时级储能电站、交通场站及重点安保区域。'],
  ['Request a Consultation', '申请技术咨询'],
  ['Explore the Product Line', '浏览产品系列'],
  ['State Key Lab of Fire Safety', '火灾科学国家重点实验室'],
  ['USTC Advanced Tech Research Institute', '中国科学技术大学先进技术研究院'],
  ['National High-Tech Enterprise', '国家高新技术企业'],
  ['Open-flame knockdown', '明火扑灭'],
  ['No re-ignition', '无复燃'],
  ['On a 48 V / 20 Ah e-vehicle lithium pack — certified by the Anhui Provincial Product Quality Supervision &amp; Research Institute.', '基于 48 V / 20 Ah 电动车锂电池包测试——经安徽省产品质量监督检验研究院认证。'],
  ['Trusted in projects with', '已服务于以下客户项目'],
  ['China Railway', '中国铁建'],
  ['Construction', '建设'],
  ['Three Gorges', '三峡'],
  ['Renewables', '新能源'],
  ['Xiamen Bus Group', '厦门公交集团'],
  ['Tiananmen District', '天安门地区'],
  ['Lithium-Battery Safety Initiative', '锂电池安全专项'],
  ['Why Lithium Fires Are Different', '锂电池火灾为何不同'],
  ['A lithium-ion fire is a chemistry problem, not just a flame problem.', '锂离子电池火灾是化学问题，而不只是火焰问题。'],
  ['Once a single cell enters thermal runaway, it ejects flammable electrolyte vapor and can propagate to neighboring cells in seconds. Dry powder, CO₂, and gaseous clean agents knock down open flame but do not cool the pack — the fire frequently reignites. Your suppression system needs to absorb heat, penetrate the pack, and keep the adjacent cells below runaway temperature.', '单个电芯一旦进入热失控，就会喷出易燃电解液蒸气，并在数秒内向相邻电芯蔓延。干粉、二氧化碳和气体灭火剂能压制明火，却无法冷却电池包，因此火灾常会复燃。抑制系统必须能够吸热、渗入电池包，并让相邻电芯保持在热失控温度以下。'],
  ['Rapid cooling, not just smothering', '快速冷却，而非仅仅窒息灭火'],
  ['Our lithium-specific foam agent is engineered as a high-stability, micro-fine foam medium with high density and low conductivity. It absorbs heat, blankets the cell, and blocks thermal radiation to adjacent cells.', '我们的锂电专用泡沫药剂采用高稳定性微细泡沫介质，具备高密度和低导电性。它可吸收热量、覆盖电芯，并阻隔向相邻电芯的热辐射。'],
  ['Early detection wins minutes', '早期探测可赢得关键时间'],
  ['Image-based flame and smoke detectors sit inside the battery cabinet and use video analytics — flame recognition, linear beam smoke, thermal — to trigger suppression before an open fire ever reaches the hall.', '图像型火焰和烟雾探测器安装在电池柜内，利用视频分析——火焰识别、线型光束感烟和热成像——在明火蔓延至建筑空间前触发抑制。'],
  ['Stop reignition after knockdown', '扑灭后防止复燃'],
  ['Our compressed-air foam (CAF) systems maintain coverage and keep reignition suppressed long after initial knockdown — critical for packs where electrolyte keeps venting after flame is gone.', '我们的压缩空气泡沫（CAF）系统可持续覆盖，并在初期扑灭后长时间抑制复燃——这对于明火消失后仍持续排放电解液的电池包至关重要。'],
  ['Product Line', '产品系列'],
  ['A full stack for battery fire safety — detection, agent, and delivery.', '电池消防安全全栈方案——探测、药剂与输送。'],
  ['Every line below was developed in-house, with the lithium-battery application as the primary design target. Portable, hand-cart, mobile, and fixed configurations are available across the range.', '以下各产品均为自主研发，并以锂电池应用为首要设计目标。全系列提供便携式、手推式、移动式和固定式配置。'],
  ['Extinguisher · Portable / Mobile / Fixed', '灭火器 · 便携式 / 移动式 / 固定式'],
  ['Lithium-Battery Dedicated Fire Extinguisher', '锂电池专用灭火器'],
  ['Purpose-engineered to release our lithium-specific foam agent directly onto burning cells. Rapidly knocks down flame, cools the cell, and reduces thermal radiation to neighboring cells — buying crews more response time.', '专为将锂电专用泡沫药剂直接喷射至燃烧电芯而设计。可快速扑灭明火、冷却电芯，并降低对相邻电芯的热辐射，为应急人员争取更多响应时间。'],
  ['Available sizes:', '可选规格：'],
  ['CAFS · 40 L – 120 L', '压缩空气泡沫系统 · 40 L–120 L'],
  ['Compressed-Air Foam System (CAFS) — Lithium', '锂电池压缩空气泡沫系统（CAFS）'],
  ['Positive-pressure three-phase gas/liquid foam generation mixes our lithium-specific foam concentrate with compressed air to form a stable, environmentally acceptable suppression medium. Fast cooling, smoke absorption, radiation blocking, high and sustained suppression.', '正压三相气液泡沫发生技术将锂电专用泡沫浓缩液与压缩空气混合，形成稳定且更具环境适应性的灭火介质。具备快速冷却、吸收烟气、阻隔辐射和高效持续抑制能力。'],
  ['Configurations:', '配置：'],
  ['Backpack &nbsp;·&nbsp; Hand-cart &nbsp;·&nbsp; Mobile (electric chassis available) &nbsp;·&nbsp; Fixed', '背负式 &nbsp;·&nbsp; 手推式 &nbsp;·&nbsp; 移动式（可选电动底盘） &nbsp;·&nbsp; 固定式'],
  ['Foam Concentrate', '泡沫浓缩液'],
  ['Lithium-Battery Foam Concentrate', '锂电池泡沫浓缩液'],
  ['Our proprietary multi-phase foam agent — high-porosity fireproof micro-components, organic phosphorus flame retardants, specialty surfactants, and a high-density, low-conductivity suppression medium. Formulated specifically for lithium-ion cell fires.', '我们的专利多相泡沫药剂由高孔隙率耐火微组分、有机磷阻燃剂、特种表面活性剂及高密度、低导电性抑制介质组成，专为锂离子电芯火灾配制。'],
  ['Also available:', '同时提供：'],
  ['AFFF &nbsp;·&nbsp; AFFF/AR (alcohol-resistant) &nbsp;·&nbsp; Class-A foam concentrate', 'AFFF &nbsp;·&nbsp; AFFF/AR（抗醇型） &nbsp;·&nbsp; A 类泡沫浓缩液'],
  ['Detection · Standard &amp; Explosion-Proof', '探测 · 标准型与防爆型'],
  ['Image-Based Flame &amp; Smoke Detection', '图像型火焰与烟雾探测'],
  ['Intelligent video-based detection using our flame-recognition algorithm. Each unit combines an industrial optical lens, HD video fire-detection module, embedded hardware, and firmware, networked over Ethernet to a central controller. Distributed detection, centralized management.', '采用自主火焰识别算法的智能视频探测。每台设备集成工业光学镜头、高清视频火灾探测模块、嵌入式硬件及固件，并通过以太网接入中央控制器，实现分布式探测、集中化管理。'],
  ['Lineup:', '产品系列：'],
  ['Flame &nbsp;·&nbsp; Linear-Beam Smoke &nbsp;·&nbsp; Thermal — each in standard and explosion-proof variants', '火焰 &nbsp;·&nbsp; 线型光束感烟 &nbsp;·&nbsp; 热成像——均提供标准型与防爆型'],
  ['Request the full product catalog', '索取完整产品目录'],
  ['Who We Serve', '服务对象'],
  ['Wherever lithium-ion is a single point of failure.', '所有将锂离子电池视为单点失效风险的场景。'],
  ['Our hardware is deployed across the four environments where a lithium fire turns a cost problem into a safety and continuity crisis.', '我们的设备已部署于四类场景：在这些场景中，锂电池火灾会从成本问题演变为安全与业务连续性危机。'],
  ['Battery Energy Storage (ESS)', '电池储能系统（ESS）'],
  ['Grid-scale, behind-the-meter, and co-located renewable sites. Container-level flooding and PACK-level precision suppression available.', '适用于电网侧、表后及新能源配套站点。可提供集装箱级全淹没和电池包级精准抑制。'],
  ['EV &amp; Battery Manufacturing', '电动汽车与电池制造'],
  ['Cell production, module assembly, aging chambers, and EV charging/swapping stations. Early detection with re-ignition control.', '适用于电芯生产、模组装配、老化房，以及电动汽车充换电站。提供早期探测与复燃控制。'],
  ['Transit &amp; Fleet', '交通与车队'],
  ['Electric bus depots, shared-mobility fleets, e-scooter &amp; e-bike charging facilities. Portable, hand-cart, and fixed options.', '适用于电动公交场站、共享出行车队及电动滑板车/电动自行车充电设施。提供便携式、手推式和固定式方案。'],
  ['Data Centers &amp; Industrial', '数据中心与工业场景'],
  ['UPS battery rooms, industrial BESS, and high-value facility protection where downtime is the business risk.', '适用于 UPS 电池间、工业储能系统以及停机即构成业务风险的高价值设施。'],
  ['Proven at Scale', '规模化验证'],
  ['From neighborhood e-bike stations to gigawatt-hour grid storage.', '从社区电动自行车充电站到吉瓦时级电网储能。'],
  ['A sample of named deployments in China across national-security, transit, and utility-scale energy storage. Full project list available on request.', '以下为我们在中国重点安保、交通和公用事业级储能领域的部分具名部署案例。完整项目清单可按需提供。'],
  ['National Security · Beijing', '重点安保 · 北京'],
  ['Tiered deployment of lithium-specific fire-safety equipment across community charging points, street patrol posts, and priority sites, plus a district-level emergency response network.', '在社区充电点、街面巡逻岗及重点场所分层部署锂电专用消防设备，并建立区域级应急响应网络。'],
  ['Fixed + portable + cart-mounted', '固定式 + 便携式 + 车载/推车式'],
  ['coverage, integrated response', '覆盖，联动响应'],
  ['Grid-Scale ESS · Shandong, China', '电网级储能 · 中国山东'],
  ['Yantai Storage Hub — 1 GW / 2 GWh ESS', '烟台储能枢纽——1 GW / 2 GWh 储能项目'],
  ['Multi-chemistry battery storage site protected with an integrated fire-safety scheme: site-wide monitoring, intelligent early warning, and automated emergency response logic.', '面向多种电池化学体系的储能站，采用一体化消防安全方案：全站监控、智能预警及自动化应急响应逻辑。'],
  ['grid-scale ESS', '电网级储能'],
  ['Transit · Fujian, China', '交通 · 中国福建'],
  ['Xiamen Bus Group — New-Energy Depot', '厦门公交集团——新能源场站'],
  ['Fire-safety protection for electric-bus parking, charging, and maintenance yards at a municipal transit operator, designed around lithium-ion thermal-runaway risk.', '为市政公交运营方的电动公交停放、充电和维修场地提供消防安全防护，围绕锂离子电池热失控风险设计。'],
  ['Municipal transit', '市政交通'],
  ['new-energy depot', '新能源场站'],
  ['Customer organizations, partners &amp; recognitions', '客户机构、合作伙伴与资质认可'],
  ['State Key Lab of Fire Safety (partner)', '火灾科学国家重点实验室（合作伙伴）'],
  ['AAA Credit Enterprise', 'AAA 级信用企业'],
  ['Asia-Pacific Forum Gold Partner', '亚太论坛金牌合作伙伴'],
  ['Anhui Software Industry Association Member', '安徽省软件行业协会会员'],
  ['Anhui Security Technology Association Member', '安徽省安全技术协会会员'],
  ['View all case studies →', '查看全部案例 →'],
  ['A research-backed manufacturer, built for the lithium era of fire safety.', '以科研为依托、面向锂电时代消防安全的制造商。'],
  ["Zhongke Yong'an is an affiliate of the University of Science and Technology of China (USTC) Advanced Technology Research Institute, drawing directly on research from the State Key Laboratory of Fire Safety. We specialize in new-energy battery fire detection, suppression devices, suppression agents, and intelligent fire-safety management platforms.", '中科永安隶属中国科学技术大学先进技术研究院，直接依托火灾科学国家重点实验室的科研成果。我们专注于新能源电池火灾探测、抑制设备、抑制药剂和智能消防安全管理平台。'],
  ['Our core technology stack — compressed-air foam generation plus a lithium-specific foam concentrate — has been translated into full solutions across electrochemical energy storage, EV charging and battery-swap infrastructure, e-bike charging canopies, and residential lithium-ion scenarios, with named deployments at central-state-owned-enterprise ESS sites and national-security zones.', '我们的核心技术体系——压缩空气泡沫发生技术加锂电专用泡沫浓缩液——已形成覆盖电化学储能、电动汽车充换电基础设施、电动自行车充电棚和住宅锂电场景的完整解决方案，并在中央国企储能项目和重点安保区域实现具名部署。'],
  ['R&amp;D-led', '研发驱动'],
  ['USTC Advanced Tech Research Institute affiliate', '中科大先进技术研究院成员单位'],
  ['Full-stack', '全栈能力'],
  ['Agent + detection + delivery, all in-house', '药剂 + 探测 + 输送，均为自主研发'],
  ['GWh-scale', '吉瓦时级'],
  ['References in grid-scale ESS projects', '拥有电网级储能项目案例'],
  ['National-level', '国家级'],
  ['Deployed in priority security zones', '已部署于重点安保区域'],
  ['Specifying fire safety for a lithium asset?', '正在为锂电资产配置消防安全方案？'],
  ['We can review your site, pack architecture, or insurance requirements and recommend the right combination of detection + agent + delivery.', '我们可审阅您的站点、电池包架构或保险要求，并推荐合适的探测 + 药剂 + 输送组合。'],
  ['Talk to an engineer', '与工程师沟通'],
  ['Get a quote or technical briefing.', '获取报价或技术说明。'],
  ["Tell us about the asset you're protecting — battery chemistry, approximate energy (kWh/MWh), application, and location. We'll come back with a recommended architecture and pricing.", '请告知需要保护的资产情况——电池化学体系、大致能量规模（kWh/MWh）、应用场景与地点。我们将回复推荐方案与报价。'],
  ['Sales contact', '销售联系人'],
  ['Mr. Yang Zhenhua', '杨振华先生'],
  ['International inquiries', '国际业务咨询'],
  ['Phone', '电话'],
  ['Mobile (English inquiries routed via form)', '手机（英文咨询请通过表单提交）'],
  ['Hotline', '服务热线'],
  ['China domestic', '中国境内'],
  ['Headquarters', '总部'],
  ['Hefei High-Tech Zone, China', '中国合肥高新区'],
  ['USTC Advanced Tech Research Institute, Future Center, 9F B907', '中科大先进技术研究院未来中心 9 楼 B907'],
  ['Factory', '工厂'],
  ['Feixi County, Hefei', '合肥市肥西县'],
  ['Economic Development Zone, Hudong Rd. No. 2', '经济开发区湖东路 2 号'],
  ['Request a consultation', '申请咨询'],
  ['We respond to qualified inquiries within one business day.', '我们将在一个工作日内回复符合条件的咨询。'],
  ['Your name', '您的姓名'],
  ['Company', '公司名称'],
  ['Work email', '工作邮箱'],
  ['Phone (with country code)', '电话（含国家/地区代码）'],
  ['Country', '国家/地区'],
  ['Application', '应用场景'],
  ['Select an industry…', '请选择行业…'],
  ['EV / Battery Manufacturing', '电动汽车 / 电池制造'],
  ['Data Center / Industrial', '数据中心 / 工业'],
  ['Distributor / Reseller', '经销商 / 代理商'],
  ['Other', '其他'],
  ['Tell us about the project', '请介绍项目情况'],
  ['Battery chemistry, approximate kWh/MWh, site location, timeline…', '电池化学体系、大致 kWh/MWh、站点地点、时间计划…'],
  ['Send inquiry', '发送咨询'],
  ["We'll never share your details. Used only to respond to your inquiry.", '我们不会分享您的资料，仅用于回复本次咨询。'],
  ["Thanks — we'll be in touch.", '感谢——我们会尽快与您联系。'],
  ['Your inquiry has been received. Our team typically responds within one business day.', '您的咨询已收到。我们的团队通常会在一个工作日内回复。'],
  ['In production this will POST to a PHP mailer / Formspree endpoint.', '正式上线时，此处将 POST 至 PHP 邮件服务 / Formspree 端点。'],
  ['For v1 preview we acknowledge the submission client-side.', '当前 v1 预览版仅在浏览器端显示提交确认。'],
];

const products = [
  ['Product Catalog — Zhongke Yong’an Battery Fire Safety', '产品目录——中科永安锂电池消防安全'],
  ["Full product catalog: lithium-battery extinguishers, foam concentrate agents, image-based flame & smoke detection, auto-tracking fire monitors, and high-pressure water-mist systems. Engineered by Zhongke Yong'an with China's State Key Laboratory for Fire Safety.", '完整产品目录：锂电池灭火器、泡沫浓缩液、图像型火焰与烟雾探测、自动跟踪消防炮及高压细水雾系统。由中科永安与中国火灾科学国家重点实验室合作研发。'],
  ['Product Catalog', '产品目录'],
  ['Engineered specifically for lithium-ion battery fire risk.', '专为锂离子电池火灾风险而研发。'],
  ['Five product lines — developed in-house — cover detection, the suppression agent itself, and every form of delivery. Battery-focused extinguishers, foam concentrates, and image-based detection form the core of the catalog. Auto-tracking cannons and high-pressure water-mist systems extend coverage into industrial facilities and high-value infrastructure. Deployed at GWh-scale energy-storage sites, transit depots, and national security zones including the <span class="kw">Tiananmen District</span> lithium-battery safety initiative.', '五条自主研发的产品线覆盖探测、抑制药剂本身及各种输送方式。以电池为重点的灭火器、泡沫浓缩液和图像型探测构成目录核心；自动跟踪消防炮和高压细水雾系统则将防护范围延伸至工业设施及高价值基础设施。已部署于吉瓦时级储能电站、交通场站及包括<span class="kw">天安门地区</span>锂电池安全专项在内的重点安保区域。'],
  ['Battery Extinguishers (10)', '电池灭火器（10）'],
  ['Foam Concentrate Agents (4)', '泡沫浓缩液（4）'],
  ['Image-Based Detection (8)', '图像型探测（8）'],
  ['Auto-Tracking Monitors (4)', '自动跟踪消防炮（4）'],
  ['High-Pressure Water Mist (4)', '高压细水雾（4）'],
  ['Category 01 · Core battery line', '类别 01 · 核心电池产品线'],
  ['Battery Extinguishers &amp; Suppression Devices', '电池灭火器与抑制设备'],
  ['10 products', '10 款产品'],
  ['Purpose-engineered to deliver our lithium-specific foam agent onto cells in thermal runaway. Portable, backpack, handcart, mobile, and fixed configurations — at both cell-level and pack-level scale.', '专为将锂电专用泡沫药剂输送至热失控电芯而设计。提供便携式、背负式、手推式、移动式和固定式配置，覆盖电芯级与电池包级。'],
  ['Featured · Portable / Mobile / Fixed', '重点产品 · 便携式 / 移动式 / 固定式'],
  ['An industrial-grade extinguisher engineered around our lithium-specific foam agent. On discharge, the agent blankets burning cells, drops cell temperature rapidly, and reduces thermal radiation and conduction to adjacent cells — cutting the chance of large-scale thermal runaway inside the pack and buying response crews more time.', '围绕锂电专用泡沫药剂研发的工业级灭火器。喷放后，药剂覆盖燃烧电芯、快速降低电芯温度，并减少向相邻电芯的热辐射和热传导，从而降低电池包内大规模热失控的可能性，为应急人员争取更多时间。'],
  ['1 L &nbsp;·&nbsp; 2 L &nbsp;·&nbsp; 6 L &nbsp;·&nbsp; 45 L · hand-cart and fixed configurations on request', '1 L &nbsp;·&nbsp; 2 L &nbsp;·&nbsp; 6 L &nbsp;·&nbsp; 45 L · 可按需提供手推式和固定式配置'],
  ['Cylinder · N₂ + Foam', '钢瓶式 · N₂ + 泡沫'],
  ['Cylinder-Type Compressed-Nitrogen Foam Extinguisher (Lithium)', '钢瓶式压缩氮气泡沫灭火器（锂电池）'],
  ['Positive-pressure three-phase gas/liquid foam technology mixes our lithium-specific foam concentrate with compressed nitrogen to form an efficient, stable, environmentally acceptable suppression medium. Fast cooling, smoke absorption, radiation blocking, sustained suppression.', '正压三相气液泡沫技术将锂电专用泡沫浓缩液与压缩氮气混合，形成高效、稳定且更具环境适应性的抑制介质。具备快速冷却、吸收烟气、阻隔辐射和持续抑制能力。'],
  ['3 L &nbsp;·&nbsp; 6 L &nbsp;·&nbsp; 30 L &nbsp;·&nbsp; larger on request', '3 L &nbsp;·&nbsp; 6 L &nbsp;·&nbsp; 30 L &nbsp;·&nbsp; 更大规格可按需提供'],
  ['CAFS · Lithium', 'CAFS · 锂电池'],
  ['Positive-pressure three-phase gas/liquid foam mixing of our lithium-specific foam concentrate with compressed air. Fast cooling, smoke absorption, radiation blocking, high extinguishing efficiency. Unit includes compressor, fire pump, electrical control, foam-liquid tank, proportional mixer, and gas/liquid mixer.', '通过正压三相气液泡沫技术将锂电专用泡沫浓缩液与压缩空气混合。具备快速冷却、吸收烟气、阻隔辐射和高灭火效率。设备包括空压机、消防泵、电控装置、泡沫液箱、比例混合器及气液混合器。'],
  ['Typical use:', '典型应用：'],
  ['battery cabinets, PACK-level fixed suppression', '电池柜、电池包级固定式抑制'],
  ['N₂ · Fixed System', 'N₂ · 固定系统'],
  ['Compressed-Nitrogen Foam Suppression System', '压缩氮气泡沫抑制系统'],
  ['For installations that require an inert pressurisation gas. Combines our lithium-specific foam concentrate with compressed nitrogen for cooling, smoke reduction, radiation blocking, and sustained suppression. Fires under program-set automatic logic.', '适用于要求使用惰性加压气体的安装场景。将锂电专用泡沫浓缩液与压缩氮气结合，实现冷却、减烟、阻隔辐射和持续抑制；按程序设定的自动逻辑触发灭火。'],
  ['Includes:', '包括：'],
  ['nitrogen cylinders, control module, water tank, foam-liquid tank', '氮气瓶、控制模块、水箱、泡沫液箱'],
  ['Fixed · E-bike charging', '固定式 · 电动自行车充电'],
  ['Fixed Foam-Spray Suppression System', '固定式泡沫喷洒抑制系统'],
  ['Designed for consolidated e-bike / e-scooter charging bays. On fire signal, the system alerts occupants and transmits to the fire-management platform; zone control valves open to the affected bay, and charging power is automatically interlocked off.', '面向集中式电动自行车 / 电动滑板车充电车位设计。收到火警信号后，系统向现场人员报警并上传至消防管理平台；分区控制阀开启受影响车位，充电电源自动联锁切断。'],
  ['e-bike / e-scooter / last-mile fleet charging points', '电动自行车 / 电动滑板车 / 末端配送车队充电点'],
  ['Backpack CAFS', '背负式 CAFS'],
  ['Backpack Compressed-Air Foam Unit', '背负式压缩空气泡沫装置'],
  ['Compressed-air composite cylinder is both the foam propellant and a firefighter air-supply source. Human-factored harness, compact envelope, hands-free — suited to tight passageways, climbing, and rescue. Works across difficult terrain.', '压缩空气复合气瓶同时作为泡沫推进剂和消防员供气源。采用人体工学背负系统，结构紧凑、可解放双手，适合狭窄通道、攀爬和救援，并可应对复杂地形。'],
  ['first responder teams, plant &amp; tunnel emergency stations', '首响应急队、厂区与隧道应急站'],
  ['Handcart CAFS', '手推式 CAFS'],
  ['Hand-Cart Compressed-Air Foam Unit', '手推式压缩空气泡沫装置'],
  ['A light, mobile positive-pressure foam-generation unit comprising cart, foam tank, proportioning mixer, delivery hardware, fire hose, control valves, and auxiliaries. Premix-type foam system.', '轻型移动式正压泡沫发生装置，由推车、泡沫液箱、比例混合器、输送组件、消防水带、控制阀及附属件构成，属于预混型泡沫系统。'],
  ['depot response cart, warehouse fire stations', '场站应急推车、仓库消防站'],
  ['Mobile CAFS', '移动式 CAFS'],
  ['Mobile Compressed-Air Foam Unit', '移动式压缩空气泡沫装置'],
  ['A wheeled/towable positive-pressure foam-generation unit including a mobile chassis, foam tank, proportioning mixer, delivery hardware, high-pressure gas cylinder, fire hose, and control valves. Premix-type foam system.', '带轮/可牵引的正压泡沫发生装置，包括移动底盘、泡沫液箱、比例混合器、输送组件、高压气瓶、消防水带及控制阀，属于预混型泡沫系统。'],
  ['yard-response units at transit depots and ESS sites', '交通场站和储能站的场区应急设备'],
  ['Mobile CAFS · Electric chassis', '移动式 CAFS · 电动底盘'],
  ['Mobile Compressed-Air Foam Unit (Electric Chassis)', '移动式压缩空气泡沫装置（电动底盘）'],
  ['Same proven CAFS architecture on a self-propelled electric chassis — the operator can drive the unit to the seat of the fire without a tow vehicle. Ideal for sprawling battery yards and indoor production floors.', '经验证的 CAFS 架构搭载自走式电动底盘——操作人员无需牵引车即可将设备驶至火源处，适合大面积电池场区和室内生产车间。'],
  ['ESS yards, manufacturing halls, large warehouses', '储能场区、制造车间、大型仓库'],
  ['Fixed CAFS', '固定式 CAFS'],
  ['Fixed Compressed-Air Foam System', '固定式压缩空气泡沫系统'],
  ['Permanently installed CAFS based on our positive-pressure three-phase foam mixing. Comprises fire pump, foam pump, air compressor, water &amp; foam tanks, proportional mixer, gas/liquid mixer, and control cabinet. For total-flooding or targeted pack-level protection.', '基于正压三相泡沫混合技术的永久安装式 CAFS。由消防泵、泡沫泵、空压机、水箱与泡沫液箱、比例混合器、气液混合器及控制柜组成，适用于全淹没或定点电池包级防护。'],
  ['container ESS, UPS rooms, industrial battery bays', '集装箱储能、UPS 机房、工业电池间'],
  ['Category 02 · Core battery line', '类别 02 · 核心电池产品线'],
  ['4 products', '4 款产品'],
  ['The chemistry inside every one of our suppression devices — plus three general-purpose foam concentrates for non-battery use cases.', '每一台抑制设备内的核心化学配方——另提供三种适用于非电池场景的通用泡沫浓缩液。'],
  ['Featured · Lithium-specific', '重点产品 · 锂电专用'],
  ['Lithium-Battery Composite Micro-Foam Concentrate', '锂电池复合微泡沫浓缩液'],
  ['A multi-phase composite formulation built for lithium-ion cell fires. Combines high-porosity fireproof micro-components, organic phosphorus flame retardants, specialty surfactants, and a high-density, low-conductivity suppression medium via a proprietary inorganic-organic compounding process.', '面向锂离子电芯火灾的多相复合配方。通过专有无机-有机复配工艺，结合高孔隙率耐火微组分、有机磷阻燃剂、特种表面活性剂及高密度、低导电性抑制介质。'],
  ['Attributes:', '特性：'],
  ['non-toxic, no persistent organic pollutants, no bioaccumulation — engineered for closed-environment battery use', '无毒、不含持久性有机污染物、无生物累积性——专为封闭环境电池应用设计'],
  ['Aqueous Film-Forming Foam (AFFF)', '水成膜泡沫液（AFFF）'],
  ['Environmentally oriented AFFF forms a water film at the fuel-surface / air interface. Very low surface tension lets the foam rapidly spread and seal the surface against oxygen, suppressing re-ignition. For crude oil, petroleum, diesel, jet fuel and similar water-insoluble flammable liquids.', '更注重环境表现的 AFFF 在燃料表面与空气界面形成水膜。极低表面张力使泡沫迅速铺展并隔绝氧气，抑制复燃。适用于原油、石油、柴油、航空煤油及类似不溶于水的易燃液体。'],
  ['fuel depots, aviation fueling, marine', '油料库、航空加油、船舶'],
  ['Alcohol-Resistant AFFF (AFFF/AR)', '抗醇型水成膜泡沫液（AFFF/AR）'],
  ['Proprietary formula for polar-solvent / water-miscible flammable liquids. Optimised foaming forms an insulating layer on the fuel surface; very low surface tension spreads the agent while its penetration depth keeps it in place rather than flowing off. Stable foam structure also supports excellent burn-back resistance.', '用于极性溶剂 / 水溶性易燃液体的专有配方。优化发泡后在燃料表面形成隔离层；极低表面张力使药剂铺展，其渗透深度可让药剂停留而非流失。稳定泡沫结构也提供优良的抗烧性能。'],
  ['alcohols, ketones, polar-solvent storage', '醇类、酮类、极性溶剂储存'],
  ['Class-A Foam Concentrate', 'A 类泡沫浓缩液'],
  ['An environmentally oriented Class-A concentrate for ordinary combustible fires. Low surface tension and good penetration let the foam wet fuel quickly and soak into wood, textiles and deep-seated fires. Stable foam structure provides sustained burn-back resistance.', '适用于普通可燃物火灾的更注重环境表现的 A 类浓缩液。低表面张力和良好渗透性使泡沫快速润湿燃料，并渗入木材、纺织品和深层火源；稳定泡沫结构提供持续抗烧性能。'],
  ['warehouse, structural, Class-A suppression systems', '仓库、建筑结构、A 类抑制系统'],
  ['Category 03 · Core battery line', '类别 03 · 核心电池产品线'],
  ['Image-Based Flame &amp; Smoke Detection', '图像型火焰与烟雾探测'],
  ['8 products', '8 款产品'],
  ['Video-based fire detection using our in-house flame / smoke / thermal recognition algorithms. Each unit combines an industrial optical lens, HD video fire-detection module, embedded hardware, and firmware, networked over Ethernet to a central controller. Distributed detection, centralised management. Every line below is available in <b style="color:#fff;">standard</b> and <b style="color:#fff;">explosion-proof</b> variants.', '采用自主火焰 / 烟雾 / 热成像识别算法的视频火灾探测。每台设备集成工业光学镜头、高清视频火灾探测模块、嵌入式硬件及固件，并通过以太网连接中央控制器，实现分布式探测、集中化管理。以下每个系列均提供<b style="color:#fff;">标准型</b>和<b style="color:#fff;">防爆型</b>。'],
  ['Flame · Standard', '火焰 · 标准型'],
  ['Image-Based Flame Detector (Standard)', '图像型火焰探测器（标准型）'],
  ['Intelligent video-based fire detection using our flame-recognition algorithm. Early-flame detection over the protected zone with dual functionality: fire detection and video surveillance.', '采用自主火焰识别算法的智能视频火灾探测。在受保护区域进行早期火焰探测，同时具备火灾探测和视频监控双重功能。'],
  ['Flame · Explosion-Proof', '火焰 · 防爆型'],
  ['Image-Based Flame Detector (Ex-Proof)', '图像型火焰探测器（防爆型）'],
  ['Explosion-proof housing for IoT-grade video flame detection in hazardous environments (petrochemical, oil &amp; gas, battery manufacturing). Same algorithm stack as the standard unit.', '为危险环境（石化、油气、电池制造）中的物联网级视频火焰探测提供防爆外壳；采用与标准型相同的算法体系。'],
  ['Linear Smoke · Standard', '线型感烟 · 标准型'],
  ['Linear-Beam Image Smoke Detector (Standard)', '线型光束图像感烟探测器（标准型）'],
  ['Non-contact opposed-beam video-image smoke detection. Early-smoke alarm with 3D volumetric coverage of the protected space; high sensitivity, strong interference immunity. Transmitter + receiver pair; each receiver can cover multiple transmitters.', '非接触式对射光束视频图像感烟探测。可对受保护空间实现三维体积覆盖的早期烟雾报警，灵敏度高、抗干扰能力强。由发射端和接收端组成，每个接收端可覆盖多个发射端。'],
  ['Linear Smoke · Explosion-Proof', '线型感烟 · 防爆型'],
  ['Linear-Beam Image Smoke Detector (Ex-Proof)', '线型光束图像感烟探测器（防爆型）'],
  ['Explosion-proof variant of the linear-beam image smoke detector for hazardous environments. Dust-, moisture- and corrosion-resistant.', '适用于危险环境的线型光束图像感烟探测器防爆型，具有防尘、防潮和耐腐蚀性能。'],
  ['Thermal · Standard', '热成像 · 标准型'],
  ['IR Thermal Imaging Fire Detector (Standard)', '红外热成像火灾探测器（标准型）'],
  ['IoT-grade IR thermal imaging detection. Uses a vanadium-oxide uncooled IR focal-plane imaging module with video-analytics and deep-learning fire recognition for early temperature, flame and smoke detection. Includes video display, control, and storage functions.', '物联网级红外热成像探测。采用氧化钒非制冷红外焦平面成像模块，结合视频分析和深度学习火灾识别，用于早期温度、火焰和烟雾探测；并包含视频显示、控制和存储功能。'],
  ['Thermal · Explosion-Proof', '热成像 · 防爆型'],
  ['IR Thermal Imaging Fire Detector (Ex-Proof)', '红外热成像火灾探测器（防爆型）'],
  ['Explosion-proof variant of the IR thermal imaging detector. Same VOx uncooled focal-plane architecture and deep-learning recognition stack, certified for hazardous environments.', '红外热成像探测器的防爆型，采用相同的 VOx 非制冷焦平面架构和深度学习识别体系，适用于危险环境。'],
  ['Smoke + Flame · Standard', '烟雾 + 火焰 · 标准型'],
  ['Smoke + Flame Combined Detector (Standard)', '烟雾 + 火焰复合探测器（标准型）'],
  ['IoT-grade AI video-based combined fire detector. Uses an AI neural-network flame-recognition algorithm for simultaneous early-flame + early-smoke detection with integrated video surveillance.', '物联网级 AI 视频复合火灾探测器。使用 AI 神经网络火焰识别算法，实现早期火焰 + 早期烟雾同步探测，并集成视频监控。'],
  ['Smoke + Flame · Ex-Proof', '烟雾 + 火焰 · 防爆型'],
  ['Smoke + Flame Combined Detector (Ex-Proof)', '烟雾 + 火焰复合探测器（防爆型）'],
  ['Explosion-proof version of the combined AI detector. Same dual-mode recognition stack with a hazardous-location housing.', '复合 AI 探测器的防爆版本，采用相同的双模式识别体系与危险场所外壳。'],
  ['Category 04 · Extended line', '类别 04 · 扩展产品线'],
  ['Auto-Tracking Positioning Fire Monitors', '自动跟踪定位消防炮'],
  ['UV/IR detection paired with digital image processing to automatically track and locate a fire in its early stages, then suppress it under automatic control. For indoor and outdoor protected zones — including hazardous and explosion-risk environments.', '紫外/红外探测结合数字图像处理，可自动跟踪并定位早期火情，再在自动控制下实施抑制。适用于室内外受保护区域，包括危险和爆炸风险环境。'],
  ['Water · Indoor / Outdoor', '水 · 室内 / 室外'],
  ['Auto-Tracking Positioning Fire Monitor', '自动跟踪定位消防炮'],
  ['IoT-grade automatic tracking / positioning / jetting suppression system. Combines the monitor head with valves, piping, pump set, end-of-line testing, intelligent controller, decoder / local control box, and operator console or wireless remote.', '物联网级自动跟踪 / 定位 / 喷射抑制系统。由炮头、阀门、管网、泵组、末端试水、智能控制器、解码器 / 现场控制箱及操作台或无线遥控器组成。'],
  ['Automatic Fire Monitor', '自动消防炮'],
  ['IoT-grade automatic fire monitor using UV/IR detection and digital image processing for flame and temperature sensing, early-fire tracking/positioning, and automatic suppression. Fixed indoor or outdoor jetting system.', '物联网级自动消防炮，采用紫外/红外探测和数字图像处理实现火焰与温度感知、早期火情跟踪/定位和自动抑制，可作为室内或室外固定喷射系统。'],
  ['Water · Explosion-Proof', '水 · 防爆型'],
  ['Explosion-Proof Automatic Fire Monitor', '防爆型自动消防炮'],
  ['IoT-grade explosion-proof automatic fire monitor for hazardous environments. UV/IR + digital-image tracking and positioning with automatic suppression, for fixed indoor/outdoor explosion-proof jetting systems.', '面向危险环境的物联网级防爆自动消防炮。通过紫外/红外 + 数字图像进行跟踪定位和自动抑制，适用于室内外固定式防爆喷射系统。'],
  ['Foam · Explosion-Proof', '泡沫 · 防爆型'],
  ['Explosion-Proof Automatic Foam Monitor', '防爆型自动泡沫消防炮'],
  ['IoT-grade electrically controlled explosion-proof automatic monitor configured for foam jetting. Same tracking / positioning / auto-suppression logic, in a hazardous-environment foam configuration.', '物联网级电控防爆自动消防炮，配置泡沫喷射功能。在危险环境泡沫方案中采用相同的跟踪 / 定位 / 自动抑制逻辑。'],
  ['Category 05 · Extended line', '类别 05 · 扩展产品线'],
  ['High-Pressure Water Mist Systems', '高压细水雾系统'],
  ['High-pressure water-mist (HPWM) hardware for facilities where water-based suppression is preferred. Fine mist rapidly absorbs heat, displaces oxygen, and scrubs combustion products — with minimal water volume and collateral damage.', '面向优先采用水基抑制的设施的高压细水雾（HPWM）设备。细水雾可快速吸热、置换氧气并洗涤燃烧产物，同时减少用水量和附带损害。'],
  ['HPWM · Pump unit', 'HPWM · 泵组'],
  ['High-Pressure Water-Mist Pump Unit', '高压细水雾泵组'],
  ['Nine-plunger high-pressure pump supply, comprising plunger pump, jockey pump, motor, control cabinet, safety/pressure-sustain valve, check valve, piping, and regulated water tank. Available in domestic and imported series. Compact, uniform flow, multi-path safety relief protection.', '九柱塞高压泵供水装置，包括柱塞泵、稳压泵、电机、控制柜、安全/持压阀、止回阀、管路和稳压水箱。提供国产与进口系列，结构紧凑、流量均匀，并具备多路安全泄压保护。'],
  ['HPWM · Zone valve', 'HPWM · 分区阀'],
  ['Zone Control Valve Box', '分区控制阀箱'],
  ['Houses motor ball valve, manual ball valve, filter, pressure switch, pressure gauge, enclosure and fittings. Receives the signal from the fire-alarm controller, opens the motor valve, releases mist into the protected zone, and feeds back status via pressure switch. Auto / manual / mechanical emergency control modes.', '内含电动球阀、手动球阀、过滤器、压力开关、压力表、箱体和接头。接收火灾报警控制器信号后开启电动阀，将细水雾释放至受保护区域，并通过压力开关反馈状态；提供自动 / 手动 / 机械应急控制模式。'],
  ['HPWM · Open nozzle', 'HPWM · 开式喷头'],
  ['High-Pressure Water-Mist Open Nozzle', '高压细水雾开式喷头'],
  ['Austenitic-stainless nozzle comprising shell and multiple centrifugal spray tips on a conical face. The swirl element inside creates rotating liquid that exits as a hollow-cone mist film — velocity differential with air breaks it into fine droplets. Wide atomisation angle, high momentum, good dispersion.', '奥氏体不锈钢喷头，由壳体及锥面上的多个离心雾化喷嘴组成。内部旋流组件形成旋转液流，以空心锥雾膜喷出；与空气的速度差将其破碎为细小液滴。雾化角大、动量高、分散性好。'],
  ['HPWM · Closed nozzle', 'HPWM · 闭式喷头'],
  ['High-Pressure Water-Mist Closed Nozzle', '高压细水雾闭式喷头'],
  ['Closed/sealed variant of the centrifugal-mist nozzle — fires when its thermal element opens. Used in pre-action or wet-pipe HPWM systems where automatic localised release is required.', '离心细水雾喷头的闭式/密封版本——感温元件动作时开启。用于需要自动局部释放的预作用或湿式高压细水雾系统。'],
  ['Need the full technical specification?', '需要完整技术规格书？'],
  ["Send us your site constraints — battery chemistry, kWh/MWh, enclosure type, ambient conditions — and we'll come back with a recommended architecture and the datasheets you need.", '请告知您的站点约束条件——电池化学体系、kWh/MWh、围护类型和环境条件——我们将回复推荐架构及所需数据表。'],
  ['Request the full catalog', '索取完整目录'],
];

const cases = [
  ['Case Studies — Zhongke Yong’an Battery Fire Safety', '案例——中科永安锂电池消防安全'],
  ["Named deployments of Zhongke Yong'an battery fire-suppression and detection systems — from Tiananmen District and China Railway Construction HQ to gigawatt-hour energy-storage sites with State Grid, Three Gorges, and major independent storage operators.", '中科永安电池火灾抑制与探测系统的具名部署案例——从天安门地区和中国铁建总部，到国家电网、三峡及大型独立储能运营商的吉瓦时级储能站。'],
  ['From neighborhood e-bike stations to gigawatt-hour grid storage.', '从社区电动自行车充电站到吉瓦时级电网储能。'],
  ['Named deployments of our lithium-specific fire-safety hardware across national-security zones, transit depots, central-government state-owned-enterprise infrastructure, and utility-scale energy storage. Featured customers include <span class="kw">Tiananmen District</span>, <span class="kw">China Railway Construction</span>, <span class="kw">State Grid</span>, <span class="kw">Three Gorges</span> Renewables, and <span class="kw">Xiamen Bus Group</span>.', '我们的锂电专用消防设备已在重点安保区域、交通场站、中央国企基础设施和公用事业级储能项目实现具名部署。重点客户包括<span class="kw">天安门地区</span>、<span class="kw">中国铁建</span>、<span class="kw">国家电网</span>、<span class="kw">三峡</span>新能源和<span class="kw">厦门公交集团</span>。'],
  ['Government &amp; National Security (4)', '政府与重点安保（4）'],
  ['Grid-Scale ESS (6)', '电网级储能（6）'],
  ['Distributed &amp; Renewable ESS (4)', '分布式与新能源配套储能（4）'],
  ['Transit &amp; Fleet (1)', '交通与车队（1）'],
  ['Named deployments', '具名部署'],
  ['Aggregate ESS protected', '已保护的储能总规模'],
  ['Central-government / SOE projects', '中央政府 / 国企项目'],
  ['Security-zone deployment', '重点安保区域部署'],
  ['Flagship Deployments', '标杆部署'],
  ['Anchor customers &amp; marquee accounts.', '核心客户与标杆项目。'],
  ['A small number of projects anchor our reputation in battery fire safety — deployments in national security zones, at central-state-owned-enterprise headquarters, and at gigawatt-hour grid storage hubs.', '少数项目奠定了我们在电池消防安全领域的口碑——它们部署于重点安保区域、中央国企总部及吉瓦时级储能枢纽。'],
  ['FLAGSHIP', '标杆'],
  ['National Security · Beijing', '重点安保 · 北京'],
  ['Tiered deployment of lithium-specific fire-safety equipment across community charging points (fixed systems), street patrol posts (portable units), and priority sites (cart-mounted units), plus a district-level emergency-response network.', '在社区充电点（固定系统）、街面巡逻岗（便携设备）和重点场所（推车式设备）分层部署锂电专用消防设备，并建立区域级应急响应网络。'],
  ['Central-SOE Headquarters · Beijing', '中央国企总部 · 北京'],
  ['China Railway Construction Group — HQ Fire-Safety Modernisation', '中国铁建集团——总部消防安全升级'],
  ['Fire-safety upgrade across headquarters buildings for the group. Tiered lithium-battery protection spanning employee charging areas, critical facilities, and a coordinated response network.', '面向集团总部建筑群的消防安全升级。分层锂电池防护覆盖员工充电区域、关键设施和协同响应网络。'],
  ['Grid-Scale ESS · Shandong', '电网级储能 · 山东'],
  ['Multi-chemistry battery storage site protected with an integrated fire-safety scheme: site-wide monitoring, intelligent early-warning, and automated emergency-response logic. One of the largest single sites in our portfolio.', '面向多种电池化学体系的储能站，采用一体化消防安全方案：全站监控、智能预警和自动化应急响应逻辑，是我们案例中规模最大的单体站点之一。'],
  ['Offshore Renewable ESS · Shandong', '海上新能源配套储能 · 山东'],
  ['Muping Offshore Wind — Companion Storage', '牟平海上风电——配套储能'],
  ['Dedicated fire-safety system for the storage assets supporting an offshore wind farm. High-reliability marine-grade protection design plus remote monitoring and maintenance.', '为海上风电场配套储能资产打造的专用消防安全系统，采用高可靠性海洋级防护设计，并提供远程监控与维护。'],
  ['Section 01', '章节 01'],
  ['Government &amp; National Security', '政府与重点安保'],
  ['4 projects', '4 个项目'],
  ['Projects where the cost of failure is political and reputational, not just financial. Our hardware is deployed in priority security zones and at central-government headquarters.', '这类项目的失效代价不仅是财务损失，更涉及政治与声誉风险。我们的设备已部署于重点安保区域和中央政府总部。'],
  ['Lithium-Battery Fire-Safety Initiative', '锂电池消防安全专项'],
  ['Tiered lithium-battery fire-safety deployment across the district — fixed suppression at community charging points, portable units at street patrol posts, cart-mounted units at priority sites, and an integrated district-level emergency-response network.', '在该区域分层部署锂电池消防安全设备——社区充电点采用固定式抑制，街面巡逻岗采用便携设备，重点场所采用推车式设备，并建立一体化区域级应急响应网络。'],
  ['Fixed + portable + cart-mounted', '固定式 + 便携式 + 推车式'],
  ['integrated response', '联动响应'],
  ['Central-SOE HQ · Beijing', '中央国企总部 · 北京'],
  ["Tiered lithium-battery fire-safety upgrade across the central headquarters of China Railway Construction Group — one of the largest state-owned enterprises in China's infrastructure sector.", '面向中国铁建集团中央总部的分层锂电池消防安全升级——该集团是中国基础设施行业最大的国有企业之一。'],
  ['Central-SOE headquarters', '中央国企总部'],
  ['multi-building scope', '多楼宇范围'],
  ['Municipal Government · Beijing', '市政政府 · 北京'],
  ['Huairou District, Miaocheng Town Government — Fire-Safety Enhancement', '怀柔区庙城镇政府——消防安全提升'],
  ["Fire-safety reinforcement at the Miaocheng Town government seat in Beijing's Huairou district. Covers staff charging and priority-building protection with our lithium-specific equipment.", '在北京市怀柔区庙城镇政府驻地实施消防安全强化，采用我们的锂电专用设备覆盖员工充电与重点建筑防护。'],
  ['Municipal government', '市政政府'],
  ['seat · Beijing', '驻地 · 北京'],
  ['Central-SOE Facility', '中央国企设施'],
  ['State Grid Training Tower — Fire-Safety Deployment', '国家电网培训大楼——消防安全部署'],
  ['Lithium-battery fire-safety protection for a State Grid training and operations facility. Detailed case write-up available on request from our engineering team.', '为国家电网培训与运营设施提供锂电池消防安全防护。详细案例说明可向我们的工程团队索取。'],
  ['State-Grid', '国家电网'],
  ['training facility', '培训设施'],
  ['Section 02', '章节 02'],
  ['Grid-Scale Energy Storage', '电网级储能'],
  ['6 projects', '6 个项目'],
  ['Utility-scale lithium-ion battery storage sites — from ~80 MWh up to 1 GW / 2 GWh. Protection schemes combine PACK-level precision suppression, cabin-level CAFS flooding, and site-level intelligent monitoring.', '公用事业级锂离子电池储能站——规模从约 80 MWh 至 1 GW / 2 GWh。防护方案结合电池包级精准抑制、舱级 CAFS 全淹没及站级智能监控。'],
  ['Shandong · 2 GWh', '山东 · 2 GWh'],
  ['Yantai Storage Hub — West · 1 GW / 2 GWh', '烟台储能枢纽——西区 · 1 GW / 2 GWh'],
  ['Multi-chemistry storage site with an integrated fire-safety scheme covering full-site monitoring, intelligent early warning, and automated emergency-response logic.', '面向多种电池化学体系的储能站，采用覆盖全站监控、智能预警和自动化应急响应逻辑的一体化消防安全方案。'],
  ['multi-chemistry', '多种电池化学体系'],
  ['Shandong · 1.6 GWh', '山东 · 1.6 GWh'],
  ['Dongying Jinhui 795 MW / 1600 MWh · Centralised Storage', '东营金汇 795 MW / 1600 MWh · 集中式储能'],
  ['Large-scale CAFS deployment — 2 fire systems integrated per container. Multi-parameter composite detection (temperature, hydrogen, VOC) plus CAFS suppression and an intelligent fire IoT monitoring platform.', '大规模 CAFS 部署——每个集装箱集成 2 套消防系统。多参数复合探测（温度、氢气、VOC）结合 CAFS 抑制与智能消防物联网监控平台。'],
  ['CAFS + multi-param detection', 'CAFS + 多参数探测'],
  ['Shandong · 200 MWh', '山东 · 200 MWh'],
  ['Shenxian, Liaocheng — 100 MW / 200 MWh Electrochemical Storage', '聊城莘县——100 MW / 200 MWh 电化学储能'],
  ['"PACK-level precision suppression + cabin-level total flooding" — one fire system per 3.45 MW / 6.709 MWh battery system, integrated in the container. PACK-level thermal-runaway detection + suppression, plus CAFS for re-ignition prevention at cabin level, under a site-wide intelligent fire platform.', '“电池包级精准抑制 + 舱级全淹没”——每套 3.45 MW / 6.709 MWh 电池系统配置一套消防系统，并集成于集装箱内。在全站智能消防平台下，实现电池包级热失控探测 + 抑制，以及舱级 CAFS 防复燃。'],
  ['PACK + cabin protection', '电池包 + 舱级防护'],
  ['Jilin · 80 MWh', '吉林 · 80 MWh'],
  ['Jidian 80 MWh — Collocated-to-Independent Storage Conversion', '吉电 80 MWh——配套储能转独立储能改造'],
  ['13 LFP battery cabins and 9 lead-carbon battery cabins, each with a dedicated fire-suppression system. Every cabin is an independent enclosure with its own fire detection and suppression, managed from a station-level intelligent fire-monitoring platform.', '13 个磷酸铁锂电池舱和 9 个铅碳电池舱，每个舱均配备专用火灾抑制系统。每个舱都是独立封闭单元，拥有独立火灾探测与抑制，并由站级智能消防监控平台统一管理。'],
  ['22 cabins · LFP + lead-carbon', '22 个舱 · 磷酸铁锂 + 铅碳'],
  ['Shandong · 400 MWh', '山东 · 400 MWh'],
  ['Dongying 2 × 200 MWh · Independent Shared Storage', '东营 2 × 200 MWh · 独立共享储能'],
  ['CAFS suppression system paired with a multi-tier fire-protection framework and intelligent monitoring and early warning.', 'CAFS 抑制系统结合多层级消防防护框架、智能监控与预警。'],
  ['independent shared storage', '独立共享储能'],
  ['Shandong · Distributed', '山东 · 分布式'],
  ['CCCC First Highway · Taian Distributed Storage', '中交一公局 · 泰安分布式储能'],
  ['Distributed energy-storage fire-safety solution for the Taian project of CCCC First Highway Engineering Bureau. PV-storage-charging-integrated safety management with an intelligent monitoring platform.', '面向中交一公局泰安项目的分布式储能消防安全解决方案。通过智能监控平台实现光储充一体化安全管理。'],
  ['Distributed ESS', '分布式储能'],
  ['PV + storage + charging', '光伏 + 储能 + 充电'],
  ['Section 03', '章节 03'],
  ['Distributed &amp; Renewable-Integrated ESS', '分布式与新能源配套储能'],
  ['Offshore-wind-integrated storage, wind-solar-storage pilots, and independent shared-storage operators — where the fire system must survive harsh environments and integrate with multi-asset energy platforms.', '海上风电配套储能、风光储试点及独立共享储能运营项目——其消防系统必须适应严苛环境，并接入多资产能源平台。'],
  ['Muping · Offshore Wind Companion Storage', '牟平 · 海上风电配套储能'],
  ['Dedicated offshore-wind-companion storage fire-safety system. High-reliability marine-grade protection design, plus remote monitoring and maintenance.', '海上风电配套储能专用消防安全系统。采用高可靠性海洋级防护设计，并支持远程监控和维护。'],
  ['Offshore wind + storage', '海上风电 + 储能'],
  ['marine-grade', '海洋级'],
  ['Shandong · Multi-energy pilot', '山东 · 多能互补试点'],
  ['Jidian Weifang Wind-Solar-Storage Multi-Energy Pilot', '吉电潍坊风光储多能互补试点'],
  ['Multi-tier fire-protection framework for a wind-solar-storage hybrid project, with integrated safety monitoring, intelligent early warning, and emergency-response handling.', '面向风光储混合项目的多层级消防防护框架，集成安全监控、智能预警与应急响应处置。'],
  ['Wind + solar + storage', '风电 + 光伏 + 储能'],
  ['hybrid safety monitoring', '混合项目安全监控'],
  ['Independent shared storage', '独立共享储能'],
  ['Independent Shared Storage — Reference Deployment', '独立共享储能——参考部署'],
  ['CAFS suppression system paired with a multi-tier fire-protection framework, intelligent monitoring, and early-warning logic.', 'CAFS 抑制系统结合多层级消防防护框架、智能监控和预警逻辑。'],
  ['Independent shared', '独立共享'],
  ['storage · CAFS', '储能 · CAFS'],
  ['Shandong · Independent ESS', '山东 · 独立储能'],
  ['Binzhou Dongli Electrical — Yangxin Independent Storage', '滨州东力电气——阳信独立储能'],
  ['CAFS deployment for explosion-prevention and suppression control. Cabin CAFS, explosion-and-fire control system, and a smart fire-management platform.', '用于防爆与抑制控制的 CAFS 部署，包括舱级 CAFS、爆炸与火灾控制系统及智能消防管理平台。'],
  ['explosion + fire control', '防爆 + 火灾控制'],
  ['Section 04', '章节 04'],
  ['Transit &amp; Fleet', '交通与车队'],
  ['1 project', '1 个项目'],
  ['Municipal new-energy bus operators and last-mile mobility fleets — where charging, parking and maintenance yards co-exist and a single battery event can compromise the whole depot.', '面向市政新能源公交运营商和末端出行车队——充电、停放与维修场地共存，单次电池事故即可影响整个场站。'],
  ['Transit · Fujian', '交通 · 福建'],
  ['— New-Energy Depot', '——新能源场站'],
  ['Need the full case-study portfolio?', '需要完整案例资料？'],
  ['Engineering write-ups, schematics, photos, and references available on request — with detail appropriate to your procurement stage, from a shortlist overview to a fully referenced technical submission.', '工程说明、图纸、照片和客户参考资料可按需提供——内容深度可匹配您的采购阶段，从初步筛选概览到带完整参考资料的技术提交。'],
  ['Request references &amp; full portfolio', '索取客户参考与完整案例资料'],
  ['Government &amp; Security', '政府与安保'],
  ['Distributed &amp; Renewable', '分布式与新能源'],
];

function transform(source, pairs) {
  const all = [...common, ...pairs].sort((a, b) => b[0].length - a[0].length);
  return all.reduce((html, [from, to]) => html.replaceAll(from, to), source);
}

const pages = [
  ['en-landing.html', 'zh-landing.html', landing],
  ['products.html', 'zh-products.html', products],
  ['cases.html', 'zh-cases.html', cases],
];

for (const [input, output, pairs] of pages) {
  const source = await readFile(input, 'utf8');
  await writeFile(output, transform(source, pairs), 'utf8');
}
